export const TUNING = {
  world: { w: 4096, h: 2304 },
  caps: { maxAnts: 4096 },
  ants: { start: 150, max: 1200 },
  factions: { player: 0, rival: 1, all: -1, count: 2 },
  spawn: { cost: 8, intervalSec: 0.6, minReserve: 10 },
  ant: {
    speed: 60,
    carryMul: 0.85,
    starveMul: 0.5,
    turnRate: 5.0,
    wanderJitter: 0.3,
    energyMax: 100,
    drainPerSec: 1.2,
    starveAt: 25,
    snackOnPickup: 15,
    refillCost: 0.5,
  },
  caste: {
    worker: 0,
    soldier: 1,
    nurse: 2,
    workerRatio: 80,
    soldierRatio: 10,
    nurseRatio: 10,
    ratioTotal: 100,
    ratioStep: 5,
    soldierScale: 1.4,
    soldierEnergyMaxMul: 2,
    soldierSpeedMul: 0.9,
    soldierPatrolRadius: 150,
    soldierPatrolSlack: 18,
    soldierDangerSenseRadius: 96,
    soldierDangerScanStrideCells: 2,
    soldierDangerThreshold: 0.035,
    soldierAttackRange: 8,
    soldierDps: 10,
    refillBelowRatio: 0.65,
    nurseNestRadiusMul: 0.72,
    nurseSpeedMul: 0.45,
    nurseWorkSecPerUnit: 4,
    broodProgressRequired: 5,
  },
  sense: { dist: 12, angleDeg: 28, dangerWeight: 2.0, homeBlend: 0.4, recruitRadius: 14 },
  pher: {
    evapFood: 0.9985,
    evapHome: 0.9985,
    evapDanger: 0.9995,
    diffuseEvery: 2,
    diffuseLerp: 0.1,
    cap: 5.0,
    depositFood: 0.3,
    depositHome: 0.12,
    pickupDecay: 0.997,
    dangerFromCorpse: 0.02,
    activeEpsilon: 0.001,
  },
  food: { clickAmount: 60, clickRadius: 24, pickupRadius: 5 },
  nest: { r: 26, startFood: 30 },
  grid: { cell: 8 },
  spatial: { cell: 32 },
  terrain: {
    moistureBlobsMin: 6,
    moistureBlobsMax: 7,
    moistureBase: 0.24,
    moistureNoise: 0.18,
    moistureBlobRadiusMin: 320,
    moistureBlobRadiusMax: 760,
    moistureBlobClusterJitter: 0.3,
    moistureBlurPasses: 3,
    moistureWetThreshold: 0.5,
    wetEvapBonus: 0.5,
    dryEvapPenalty: 1.5,
    rockyRegionsMin: 2,
    rockyRegionsMax: 3,
    rockyRegionStartDistance: 380,
    rockyRegionDistanceStep: 220,
    rockyRegionSpanMin: 160,
    rockyRegionSpanMax: 240,
    rockyRegionSpacing: 68,
    rockyRegionGapHalfWidth: 78,
    rockyRegionRadialJitter: 26,
    rockyRegionAngleJitter: 0.24,
    rockyRegionExtraBoulders: 2,
    rockyBoulderMinRadius: 18,
    rockyBoulderMaxRadius: 32,
  },
  ecology: {
    bushMin: 14,
    bushMax: 14,
    bushMoistureMin: 0.5,
    bushCap: 40,
    bushInitialMin: 40,
    bushInitialMax: 40,
    bushRegrowSec: 3,
    bushScentDeposit: 0.24,
    bushScentRadius: 48,
    bushClearRadius: 12,
    bushFoodRadius: 18,
    bushMinNestDist: 180,
    bushMaxNestDist: 980,
    bushMinSpacing: 72,
    bushPreferredRadius: 48,
    bushPlacementAttempts: 900,
    carcassMinSec: 120,
    carcassMaxSec: 240,
    carcassAmount: 300,
    carcassDecaySec: 90,
    carcassSpoilSec: 30,
    carcassDangerDeposit: 0.035,
    carcassScentDeposit: 0.45,
    carcassScentRadius: 72,
    carcassRadius: 34,
    carcassMidDistMin: 320,
    carcassMidDistMax: 900,
    carcassAngleJitter: 0.55,
    carcassPlacementAttempts: 240,
    carcassToastSec: 3.2,
  },
  seasons: {
    yearSec: 480,
    seasonSec: 120,
    clockMinuteSec: 60,
    spring: 0,
    summer: 1,
    fall: 2,
    winter: 3,
    springBushRegrowMul: 1.5,
    summerBushRegrowMul: 1,
    fallEnergyDrainMul: 1.2,
    fallBushRegrowMul: 0.5,
    fallCarcassChanceMul: 1.5,
    winterBushRegrowMul: 0,
    winterEnergyDrainMul: 1.6,
    winterSpeedMul: 0.8,
    winterReserveHint: 150,
    rainMinSec: 10,
    rainMaxSec: 20,
    rainCheckSec: 1,
    rainSpringChancePerSec: 0.0048,
    rainSummerChancePerSec: 0.0009,
    rainFallChancePerSec: 0.0058,
    rainWinterChancePerSec: 0,
    rainPherFoodMul: 0.97,
    rainToastSec: 2.6,
    rainToastText: "Rain",
    rainStreakCount: 36,
    rainStreakLength: 42,
    rainStreakSlant: 0.28,
    rainStreakWidth: 1,
    rainStreakAlpha: 0.13,
    rainStreakSpeed: 74,
    springTint: "#f3f7ec",
    summerTint: "#ffffff",
    fallTint: "#fff2da",
    winterTint: "#d9e0dc",
    rainTint: "#c9cbc0",
  },
  corpse: { decaySec: 25 },
  fx: { maxParticles: 400, shakeDecay: 1.5 },
  ui: { hudHz: 5, telemetryHz: 2, chartSamples: 120 },
  controls: {
    drawerWidth: 280,
    sliders: {
      pherEvapFood: { min: 0.995, max: 0.9999, step: 0.0001, precision: 4 },
      pherEvapHome: { min: 0.995, max: 0.9999, step: 0.0001, precision: 4 },
      pherEvapDanger: { min: 0.998, max: 0.9999, step: 0.0001, precision: 4 },
      pherDiffuseLerp: { min: 0, max: 0.3, step: 0.01, precision: 2 },
      pherDepositFood: { min: 0.05, max: 1, step: 0.05, precision: 2 },
      pherPickupDecay: { min: 0.99, max: 0.9995, step: 0.0001, precision: 4 },
      senseDist: { min: 6, max: 24, step: 1, precision: 0 },
      senseAngleDeg: { min: 10, max: 60, step: 1, precision: 0 },
      antDrainPerSec: { min: 0.3, max: 3, step: 0.1, precision: 1 },
      antStarveAt: { min: 5, max: 60, step: 1, precision: 0 },
      spawnCost: { min: 2, max: 20, step: 1, precision: 0 },
      spawnIntervalSec: { min: 0.2, max: 2, step: 0.1, precision: 1 },
      antsMax: { min: 50, max: 4096, step: 1, precision: 0 },
    },
    presets: {
      harsh: { drainPerSec: 2.2, evapFood: 0.997 },
      abundance: { cost: 4, clickAmount: 60 },
    },
  },
  spider: {
    hp: 100,
    spawnMinSec: 90,
    spawnMaxSec: 150,
    lifetimeSec: 60,
    edgePadding: 24,
    edgeCount: 4,
    edgeTop: 0,
    edgeRight: 1,
    edgeBottom: 2,
    edgeLeft: 3,
    speed: 38,
    turnRate: 2.6,
    wanderJitter: 0.7,
    trafficSenseRadius: 140,
    trafficSampleStride: 3,
    killRadius: 10,
    eatPauseSec: 1,
    dangerRadius: 60,
    dangerDeposit: 0.22,
    killDanger: 1.4,
    fleeTurnRateMul: 3.5,
    edgeInwardBlend: 0.4,
    minSampleStride: 1,
    trophyFood: 5,
    squashTrauma: 0.2,
    squashRadius: 7,
    toastSec: 2.4,
    toastFadeSec: 0.45,
    toastText: "⚠ Spider",
    toastW: 108,
    toastH: 28,
    toastTop: 14,
    toastFontPx: 13,
    drawRingAlpha: 0.14,
    drawShadowAlpha: 0.32,
    drawShadowRadiusXMul: 1.45,
    drawShadowRadiusYMul: 0.45,
    drawBodyRadius: 7,
    drawAbdomenRadius: 6,
    drawHeadRadius: 4.4,
    drawHeadRadiusYMul: 0.82,
    drawHeadOffset: 5.3,
    drawAbdomenOffset: -3.8,
    drawEyeForward: 2.2,
    drawEyeSide: 1.35,
    drawEyeRadius: 1,
    drawLegPairs: 4,
    drawLegSpacing: 3.6,
    drawLegRootY: 3.4,
    drawLegLength: 11,
    drawLegWiggleSpeed: 8,
    drawLegWiggleAmount: 1.8,
    drawLineWidth: 1.25,
    drawToastLineWidth: 1,
  },
  queen: {
    starvationSec: 60,
    terminalCascadeSec: 30,
  },
  rival: {
    start: 150,
    cornerPaddingX: 430,
    cornerPaddingY: 330,
    dripAmount: 80,
    dripSec: 45,
    dripRadius: 46,
    dripSpread: 200,
    workerRatio: 60,
    soldierRatio: 20,
    nurseRatio: 20,
    midlineCarcassJitter: 260,
    midlineCarcassAlong: 220,
    nestPulseImpulse: 0.32,
  },
  conflict: {
    range: 6,
    soldierKillsWorkerSec: 1,
    peerKillSec: 3,
    dangerDeposit: 1.1,
    dangerRadius: 20,
  },
  time: { stepHz: 60, maxFrameMs: 50, maxStepsPerFrame: 8, msPerSec: 1000 },
  seed: { value: 1337 },
  sim: {
    minWidth: 320,
    minHeight: 260,
    initialScatterRadius: 60,
    initialForagerRatio: 0.75,
    initialHeadingJitter: 0.45,
    recruitJitter: 0.5,
    staleTrailSec: 6,
    staleIgnoreSec: 3,
    staleDangerSec: 1,
    staleDangerDeposit: 0.1,
    excitementSec: 2,
    excitementSpeedMul: 1.4,
    excitementHomeMul: 2,
    foodClusters: [
      { dist: 220, angle: -0.9, amount: 220, radius: 26 },
      { dist: 360, angle: 2.55, amount: 260, radius: 28 },
      { dist: 520, angle: 0.72, amount: 320, radius: 34 },
      { dist: 640, angle: -2.15, amount: 280, radius: 30 },
      { dist: 780, angle: 1.72, amount: 340, radius: 36 },
      { dist: 900, angle: -0.08, amount: 360, radius: 38 },
    ],
    obstacles: [
      { dist: 210, angle: -0.2, r: 42 },
      { dist: 260, angle: -0.04, r: 48 },
      { dist: 315, angle: 0.12, r: 44 },
      { dist: 390, angle: 0.26, r: 52 },
      { dist: 245, angle: 2.3, r: 40 },
      { dist: 305, angle: 2.48, r: 46 },
      { dist: 370, angle: 2.66, r: 43 },
      { dist: 455, angle: 2.84, r: 50 },
      { dist: 550, angle: -1.45, r: 38 },
      { dist: 650, angle: 1.05, r: 54 },
    ],
    spawnRimJitter: 0.32,
    sensorThreshold: 0.025,
    foodSeekAmount: 0.05,
    sampleFoodWeak: 0.42,
    obstacleAhead: 10,
    obstacleMargin: 4,
    obstacleSensorMargin: 16,
    obstacleSensorWeight: 3.5,
    obstacleAvoidTurn: 2.2,
    obstacleEscapeJitter: 0.35,
    obstaclePushPadding: 0.5,
    edgeMargin: 30,
    edgeBlend: 0.75,
    minTurnEpsilon: 0.0001,
    randomTurnHalf: 0.5,
    tau: Math.PI * 2,
    halfPi: Math.PI * 0.5,
    deathDanger: 1.4,
    deathsBurstWindowSec: 1,
    deathsBurstCount: 5,
    traumaBurst: 0.3,
    nestPulseImpulse: 0.48,
    nestPulseDamping: 0.86,
    nestPulseSpring: 22,
    deliveryWindowSec: 60,
    fpsEma: 0.12,
  },
  input: {
    boulderMinRadius: 14,
    boulderMaxRadius: 22,
    washRadius: 40,
    dragSpacing: 10,
    cursorUnset: -10000,
  },
  tools: {
    lureStrength: 2.0,
    lureRadius: 18,
    lureEvapMultiplier: 4,
    lureStrokeSpacing: 8,
    digRadius: 20,
    digCooldownSec: 3,
    carcassDropCooldownSec: 90,
  },
  camera: {
    minZoom: 0.4,
    maxZoom: 2.5,
    zoomStep: 1.12,
    wheelZoomBase: 0.0015,
    keyPanPx: 72,
  },
  debug: { stressSpawnAnts: 500 },
  minimap: {
    w: 192,
    h: 108,
    left: 12,
    bottom: 104,
    border: 1,
    viewportLineWidth: 1,
    dotNest: 3,
    dotFood: 2,
  },
  render: {
    maxDpr: 2,
    backgroundPebblesPerMegaPixel: 820,
    backgroundPebbleMin: 0.35,
    backgroundPebbleRange: 1.3,
    backgroundVignetteInner: 0.1,
    backgroundVignetteOuter: 0.75,
    moistureTintAlpha: 0.22,
    seasonRainTintMix: 0.18,
    pherUpdateEvery: 2,
    pherAlpha: 0.85,
    rivalPherAlpha: 0.72,
    foodDotsMin: 2,
    foodDotsRange: 3,
    foodDotRadius: 1.25,
    foodTwinkleSpeed: 3,
    foodTwinkleAmp: 0.35,
    foodTwinkleBase: 0.55,
    foodRenderMaxCells: 900,
    bushDrawRadius: 10,
    bushShadowAlpha: 0.3,
    bushBranchCount: 5,
    bushBranchLength: 12,
    bushBerryMaxSparkles: 8,
    bushBerryRadius: 1.1,
    carcassDrawRadius: 20,
    carcassRibCount: 4,
    carcassSpoilPulseSpeed: 7,
    carcassEventRingRadius: 72,
    carcassEventRingAlpha: 0.34,
    obstacleRoughPoints: 18,
    obstacleRoughness: 0.12,
    obstacleShadowOffset: 0.34,
    corpseAlphaFloor: 0.12,
    nestRingBase: 1,
    nestRingPulse: 0.15,
    queenOffsetX: -7,
    queenOffsetY: 4,
    queenRadiusX: 14,
    queenRadiusY: 5,
    queenVeilRadiusX: 18,
    queenVeilRadiusY: 8,
    eggClutchRadius: 10,
    eggDotRadius: 1.3,
    eggDotCount: 9,
    eggRingAlpha: 0.42,
    antSpriteScale: 2,
    antBodyWobbleDistance: 0.5,
    antBodyWobbleAmount: 0.06,
    antSpriteW: 22,
    antSpriteH: 12,
    antDrawW: 15,
    antDrawH: 8,
    terminalAntTint: "#8f8980",
    crumbOffset: 8,
    crumbSize: 2,
    particleGravity: 8,
    particleDrag: 0.985,
    particleMinLife: 0.18,
    particleCanvasPadding: 64,
    shakePixels: 4,
    previewLineDash: 5,
    fallbackFontPx: 14,
    chartW: 360,
    chartH: 74,
    chartPad: 6,
    statPopMs: 250,
  },
  particles: {
    spawn: { count: 5, speed: 28, life: 0.45, size: 1.4 },
    nest: { count: 3, speed: 44, life: 0.65, size: 1.6 },
    death: { count: 10, speed: 34, life: 0.7, size: 1.8 },
    dust: { count: 18, speed: 58, life: 0.62, size: 2.2 },
    wash: { count: 20, speed: 72, life: 0.55, size: 1.2 },
    spiderSquash: { count: 28, speed: 74, life: 0.72, size: 2.1 },
  },
  colors: {
    soil: "#14100c",
    soilDark: "#080706",
    soilWarm: "#211810",
    soilWet: "#182017",
    soilDry: "#120d08",
    pebble: "#3a342e",
    panel: "#101010",
    panel2: "#171717",
    border: "#303030",
    text: "#eeeeea",
    muted: "#9b9a91",
    accent: "#8f9482",
    active: "#d8d3b0",
    food: "#ffb347",
    food2: "#d6dc79",
    bush: "#182316",
    bushDark: "#0a0d08",
    berry: "#c1b56a",
    carcass: "#2b1710",
    carcassBone: "#b7aa89",
    carcassSpoil: "#7f8a54",
    home: "#4dd8ff",
    danger: "#ff4d3d",
    ant: "#6d4a2f",
    antDark: "#24160d",
    starving: "#c9b99b",
    corpse: "#17110e",
    stone: "#4d4b46",
    stoneDark: "#23221f",
    stoneLight: "#77736b",
    spider: "#090706",
    spiderLeg: "#1f1712",
    spiderEye: "#d8d3b0",
    spiderToast: "#2a1412",
    soldier: "#9a6c45",
    nurse: "#8b7a5a",
    queen: "#7b5635",
    egg: "#cdbd82",
    gameOver: "#050505",
    victory: "#07080a",
    rivalAnt: "#8a849c",
    rivalTrailFood: "#b6a5d4",
    rivalTrailHome: "#8d86ba",
    rivalNest: "#3b354c",
    rivalQueen: "#6b6082",
    rivalEgg: "#aaa1bd",
    nest: "#5b3f25",
    nestDark: "#0c0907",
    nestRing: "#c9b16d",
    preview: "#d7d1ba",
    fallback: "#f0eee4",
  },
} as const;

type Mutable<T> = { -readonly [K in keyof T]: Mutable<T[K]> };

function deepClone<T>(value: T): Mutable<T> {
  if (Array.isArray(value)) {
    return value.map((item) => deepClone(item)) as Mutable<T>;
  }
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(value)) {
      out[key] = deepClone((value as Record<string, unknown>)[key]);
    }
    return out as Mutable<T>;
  }
  return value as Mutable<T>;
}

function deepFreeze<T>(value: T): Readonly<T> {
  if (value && typeof value === "object") {
    Object.freeze(value);
    for (const key of Object.keys(value)) {
      deepFreeze((value as Record<string, unknown>)[key]);
    }
  }
  return value;
}

export const DEFAULTS = deepFreeze(deepClone(TUNING));
